permalink: /:year-:month-:day-:title.html
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: ivyxjc
  email: ivyxjc1994@hotmail.com
  link: ivyxjc.xyz
  github: https://github.com/ivyxjc

# 站点信息
title: Ivyxjc
description: My personal blog
url: https://ivyxjc.xyz
enforce_ssl: ivyxjc.xyz
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /assets/img/identicon.png
favicon: /assets/img/identicon.png

# google analytics 设置
ga:
  id: UA-73862242-1
  url: ivyxjc.xyz

# disqus 设置
disqus:
  shortname: 

# 主题设置，自动激活某个标签
active:

# 首页除了最新文章外显示分类
cates:  
  - OJ
  - Web
  - Android

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

gems: [jekyll-paginate]